<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SchoolClass;
class SchoolClassSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $classes = [
                ['name' => 'Please Select'],
                ['name' => 'Diploma/Certifications'],
                ['name' => 'A Level'],
                ['name' => 'ACCA'],
                ['name' => 'IGCSE'],
                ['name' => 'Class 1 to 5'],
                ['name' => 'Class 6 to 8'],
                ['name' => 'Matric'],
                ['name' => 'Intermediate'],
                ['name' => 'O Level'],
                ['name' => 'Bachelors'],
                ['name' => 'Masters'],
                ['name' => 'PhD'],
                ['name' => 'Postdoctoral'],
                ['name' => 'GED'],
                ['name' => 'High School Diploma'],
                ['name' => 'Associate Degree'],
                ['name' => 'MBA'],
                ['name' => 'MD (Doctor of Medicine)'],
                ['name' => 'JD (Juris Doctor)'],
                ['name' => 'Bar Exam'],
                ['name' => 'CPA (Certified Public Accountant)'],
                ['name' => 'CFA (Chartered Financial Analyst)'],
                ['name' => 'IELTS/TOEFL'],
                ['name' => 'Language Training'],
                ['name' => 'Quran'],
                ['name' => 'Technical Certifications (e.g., Cisco, AWS, Microsoft)'],
                ['name' => 'Vocational Training'],
                ['name' => 'Trade School'],
                ['name' => 'Nursing Degree'],
                ['name' => 'Pharmacy Degree'],
                ['name' => 'Engineering Certifications'],
                ['name' => 'Pilot License'],
                ['name' => 'Military Training'],
                ['name' => 'Apprenticeship Programs'],
                ['name' => 'Online Course Certificates (e.g., Coursera, Udacity)'],
                ['name' => 'Music Degree'],
                ['name' => 'Fine Arts Degree'],
                ['name' => 'Sports Coaching Certification'],
                ['name' => 'Yoga Instructor Certification'],
                ['name' => 'Artificial Intelligence Certification'],
                ['name' => 'Data Science Degree'],
                ['name' => 'Cybersecurity Certification'],
                ['name' => 'Cloud Computing Certification'],
                ['name' => 'Blockchain Certification'],
                ['name' => 'Digital Marketing Certification'],
                ['name' => 'Project Management Professional (PMP)'],
                ['name' => 'Six Sigma Certification'],
                ['name' => 'Scrum Master Certification'],
                ['name' => 'DevOps Certification'],
                ['name' => 'UI/UX Design Certification'],
                ['name' => '3D Animation Degree'],
                ['name' => 'Film Production Degree'],
                ['name' => 'Journalism Degree'],
                ['name' => 'Creative Writing Certification'],
                ['name' => 'Public Speaking Certification'],
                ['name' => 'Social Work Degree'],
                ['name' => 'Psychology Degree'],
                ['name' => 'Environmental Science Degree'],
                ['name' => 'Agriculture Degree'],
                ['name' => 'Hospitality Management'],
                ['name' => 'Event Management'],
                ['name' => 'Culinary Arts Degree'],
                ['name' => 'Fashion Design Degree'],
                ['name' => 'Interior Design Degree'],
                ['name' => 'Architecture Degree'],
                ['name' => 'Urban Planning Degree'],
                ['name' => 'Astronomy Degree'],
                ['name' => 'Physics Degree'],
                ['name' => 'Mathematics Degree'],
                ['name' => 'Statistics Degree'],
                ['name' => 'Chemistry Degree'],
                ['name' => 'Biology Degree'],
                ['name' => 'Geology Degree'],
                ['name' => 'Marine Biology Degree'],
                ['name' => 'Anthropology Degree'],
                ['name' => 'Archaeology Degree'],
                ['name' => 'History Degree'],
                ['name' => 'Political Science Degree'],
                ['name' => 'Economics Degree'],
                ['name' => 'Sociology Degree'],
                ['name' => 'Philosophy Degree'],
                ['name' => 'Theology Degree'],
                ['name' => 'Linguistics Degree'],
                ['name' => 'Literature Degree'],
                ['name' => 'Graphic Design Degree'],
                ['name' => 'Web Development Certification'],
                ['name' => 'Game Design Degree'],
                ['name' => 'Mobile App Development'],
                ['name' => 'Electrical Engineering Degree'],
                ['name' => 'Mechanical Engineering Degree'],
                ['name' => 'Civil Engineering Degree'],
                ['name' => 'Chemical Engineering Degree'],
                ['name' => 'Biomedical Engineering'],
                ['name' => 'Aerospace Engineering'],
                ['name' => 'Automotive Engineering'],
                ['name' => 'Robotics Certification'],
                ['name' => 'Nanotechnology Degree'],
                ['name' => 'Renewable Energy Certification'],
                ['name' => 'Quantum Computing Certification'],
                ['name' => 'Supply Chain Management'],
                ['name' => 'Business Analytics'],
                ['name' => 'Financial Planning Certification'],
                ['name' => 'Investment Banking Certification'],
                ['name' => 'Actuarial Science Degree'],
                ['name' => 'Real Estate Certification'],
                ['name' => 'Legal Assistant Certification'],
                ['name' => 'Forensic Science Degree'],
                ['name' => 'Criminology Degree'],
                ['name' => 'Public Administration Degree'],
                ['name' => 'International Relations Degree'],
                ['name' => 'Education Degree'],
                ['name' => 'Special Education Certification'],
                ['name' => 'Counseling Certification'],
                ['name' => 'Health Informatics Certification'],
                ['name' => 'Nutrition Certification'],
                ['name' => 'Occupational Therapy Degree'],
                ['name' => 'Physical Therapy Degree'],
                ['name' => 'Speech Pathology Degree'],
                ['name' => 'Veterinary Medicine Degree'],
                ['name' => 'Dentistry Degree'],
                ['name' => 'Optometry Degree'],
                ['name' => 'Chiropractic Degree'],
                ['name' => 'Midwifery Certification'],
                ['name' => 'Medical Coding Certification'],
                ['name' => 'Phlebotomy Certification'],
                ['name' => 'Radiologic Technology Certification'],
                ['name' => 'EMT Certification'],
                ['name' => 'Firefighter Certification'],
                ['name' => 'Law Enforcement Training'],
                ['name' => 'Private Investigator Certification'],
                ['name' => 'Cyber Forensics Certification'],
                ['name' => 'Emergency Management Certification'],
                ['name' => 'Disaster Recovery Certification'],
                ['name' => 'Human Resources Certification'],
                ['name' => 'Diversity and Inclusion Certification'],
                ['name' => 'Corporate Governance Certification'],
                ['name' => 'Leadership and Management Certification'],
                ['name' => 'Negotiation and Conflict Resolution'],
                ['name' => 'Ethics and Compliance Certification'],
                ['name' => 'Intellectual Property Law Certification']            
        ];
        foreach ($classes as $class) {
            SchoolClass::create($class);
        }
    }
}
