<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SchoolClass;
class SchoolClassSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $classes = [
            ['name' => '3D Animation Degree'],
            ['name' => 'A Level'],
            ['name' => 'ACCA'],
            ['name' => 'Actuarial Science Degree'],
            ['name' => 'Advanced Placement (AP)'],
            ['name' => 'Aerospace Engineering'],
            ['name' => 'Agriculture Degree'],
            ['name' => 'Anthropology Degree'],
            ['name' => 'Apprenticeship Programs'],
            ['name' => 'Architecture Degree'],
            ['name' => 'Artificial Intelligence Certification'],
            ['name' => 'Associate Degree'],
            ['name' => 'Astronomy Degree'],
            ['name' => 'Automotive Engineering'],
            ['name' => 'Bachelors'],
            ['name' => 'Bar Exam'],
            ['name' => 'Biology Degree'],
            ['name' => 'Biomedical Engineering'],
            ['name' => 'Blockchain Certification'],
            ['name' => 'Business Analytics'],
            ['name' => 'Certified Financial Analyst (CFA)'],
            ['name' => 'Certified Public Accountant (CPA)'],
            ['name' => 'Chemical Engineering Degree'],
            ['name' => 'Chemistry Degree'],
            ['name' => 'Chiropractic Degree'],
            ['name' => 'CFA (Chartered Financial Analyst)'],
            ['name' => 'Civil Engineering Degree'],
            ['name' => 'Cloud Computing Certification'],
            ['name' => 'Class 1 to 5'],
            ['name' => 'Class 6 to 8'],
            ['name' => 'Corporate Governance Certification'],
            ['name' => 'Counseling Certification'],
            ['name' => 'Creative Writing Certification'],
            ['name' => 'Criminology Degree'],
            ['name' => 'Culinary Arts Degree'],
            ['name' => 'Cyber Forensics Certification'],
            ['name' => 'Cybersecurity Certification'],
            ['name' => 'Data Science Degree'],
            ['name' => 'Dentistry Degree'],
            ['name' => 'DevOps Certification'],
            ['name' => 'Digital Marketing Certification'],
            ['name' => 'Diploma/Certifications'],
            ['name' => 'Disaster Recovery Certification'],
            ['name' => 'Diversity and Inclusion Certification'],
            ['name' => 'Economics Degree'],
            ['name' => 'Education Degree'],
            ['name' => 'Electrical Engineering Degree'],
            ['name' => 'Emergency Management Certification'],
            ['name' => 'EMT Certification'],
            ['name' => 'Engineering Certifications'],
            ['name' => 'Environmental Science Degree'],
            ['name' => 'Ethics and Compliance Certification'],
            ['name' => 'Event Management'],
            ['name' => 'Fashion Design Degree'],
            ['name' => 'Film Production Degree'],
            ['name' => 'Fine Arts Degree'],
            ['name' => 'Financial Planning Certification'],
            ['name' => 'Firefighter Certification'],
            ['name' => 'Forensic Science Degree'],
            ['name' => 'Game Design Degree'],
            ['name' => 'GED'],
            ['name' => 'Geology Degree'],
            ['name' => 'Graphic Design Degree'],
            ['name' => 'Health Informatics Certification'],
            ['name' => 'High School Diploma'],
            ['name' => 'History Degree'],
            ['name' => 'Hospitality Management'],
            ['name' => 'Human Resources Certification'],
            ['name' => 'IELTS/TOEFL'],
            ['name' => 'IGCSE'],
            ['name' => 'Industrial Engineering Degree'],
            ['name' => 'Information Technology Degree'],
            ['name' => 'Insurance and Risk Management'],
            ['name' => 'Interior Design Degree'],
            ['name' => 'International Relations Degree'],
            ['name' => 'Investment Banking Certification'],
            ['name' => 'Journalism Degree'],
            ['name' => 'JD (Juris Doctor)'],
            ['name' => 'Language Training'],
            ['name' => 'Law Enforcement Training'],
            ['name' => 'Legal Assistant Certification'],
            ['name' => 'Leadership and Management Certification'],
            ['name' => 'Linguistics Degree'],
            ['name' => 'Literature Degree'],
            ['name' => 'Mathematics Degree'],
            ['name' => 'Masters'],
            ['name' => 'MD (Doctor of Medicine)'],
            ['name' => 'Mechanical Engineering Degree'],
            ['name' => 'Medical Coding Certification'],
            ['name' => 'Midwifery Certification'],
            ['name' => 'Military Training'],
            ['name' => 'Mobile App Development'],
            ['name' => 'Music Degree'],
            ['name' => 'Nanotechnology Degree'],
            ['name' => 'Negotiation and Conflict Resolution'],
            ['name' => 'Nursing Degree'],
            ['name' => 'Nutrition Certification'],
            ['name' => 'Occupational Therapy Degree'],
            ['name' => 'O Level'],
            ['name' => 'Online Course Certificates (e.g., Coursera, Udacity)'],
            ['name' => 'Optometry Degree'],
            ['name' => 'Pharmacy Degree'],
            ['name' => 'Philosophy Degree'],
            ['name' => 'PhD'],
            ['name' => 'Phlebotomy Certification'],
            ['name' => 'Physical Therapy Degree'],
            ['name' => 'Physics Degree'],
            ['name' => 'Pilot License'],
            ['name' => 'Please Select'],
            ['name' => 'Political Science Degree'],
            ['name' => 'Postdoctoral'],
            ['name' => 'Private Investigator Certification'],
            ['name' => 'Project Management Professional (PMP)'],
            ['name' => 'Psychology Degree'],
            ['name' => 'Public Administration Degree'],
            ['name' => 'Public Speaking Certification'],
            ['name' => 'Quran'],
            ['name' => 'Quantum Computing Certification'],
            ['name' => 'Radiologic Technology Certification'],
            ['name' => 'Real Estate Certification'],
            ['name' => 'Renewable Energy Certification'],
            ['name' => 'Robotics Certification'],
            ['name' => 'Scrum Master Certification'],
            ['name' => 'Six Sigma Certification'],
            ['name' => 'Social Work Degree'],
            ['name' => 'Sociology Degree'],
            ['name' => 'Special Education Certification'],
            ['name' => 'Speech Pathology Degree'],
            ['name' => 'Sports Coaching Certification'],
            ['name' => 'Statistics Degree'],
            ['name' => 'Supply Chain Management'],
            ['name' => 'Technical Certifications (e.g., Cisco, AWS, Microsoft)'],
            ['name' => 'Theology Degree'],
            ['name' => 'Trade School'],
            ['name' => 'UI/UX Design Certification'],
            ['name' => 'Urban Planning Degree'],
            ['name' => 'Veterinary Medicine Degree'],
            ['name' => 'Vocational Training'],
            ['name' => 'Web Development Certification'],
            ['name' => 'Yoga Instructor Certification']
        ];
        foreach ($classes as $class) {
            SchoolClass::create($class);
        }
    }
}
