<?php

return [
    'countries' => [
        'AF' => 12, // Afghanistan: +93 (3 prefix digits + 9 number digits)
        'AL' => 12, // Albania: +355 (3 prefix digits + 9 number digits)
        'DZ' => 12, // Algeria: +213 (3 prefix digits + 9 number digits)
        'AS' => 11, // American Samoa
        'AD' => 12, // Andorra
        'AO' => 12, // Angola
        'AI' => 11, // Anguilla
        'AQ' => 11, // Antarctica
        'AG' => 11, // Antigua and Barbuda
        'AR' => 12, // Argentina
        'AM' => 11, // Armenia
        'AW' => 11, // Aruba
        'AU' => 12, // Australia: +61 (3 prefix digits + 9 number digits)
        'AT' => 12, // Austria
        'AZ' => 12, // Azerbaijan
        'BS' => 11, // Bahamas
        'BH' => 12, // Bahrain
        'BD' => 13, // Bangladesh: +880 (3 prefix digits + 10 number digits)
        'BB' => 11, // Barbados
        'BY' => 12, // Belarus
        'BE' => 12, // Belgium
        'BZ' => 11, // Belize
        'BJ' => 11, // Benin
        'BM' => 11, // Bermuda
        'BT' => 11, // Bhutan
        'BO' => 12, // Bolivia
        'BA' => 11, // Bosnia and Herzegovina
        'BW' => 12, // Botswana
        'BV' => 11, // Bouvet Island
        'BR' => 13, // Brazil: +55 (3 prefix digits + 10 number digits)
        'IO' => 11, // British Indian Ocean Territory
        'BN' => 12, // Brunei Darussalam
        'BG' => 12, // Bulgaria
        'BF' => 11, // Burkina Faso
        'BI' => 11, // Burundi
        'KH' => 11, // Cambodia
        'CM' => 11, // Cameroon
        'CA' => 12, // Canada: +1 (2 prefix digits + 10 number digits)
        'CV' => 11, // Cape Verde
        'KY' => 11, // Cayman Islands
        'CF' => 11, // Central African Republic
        'TD' => 11, // Chad
        'CL' => 11, // Chile
        'CN' => 13, // China: +86 (3 prefix digits + 10 number digits)
        'CX' => 11, // Christmas Island
        'CC' => 11, // Cocos (Keeling) Islands
        'CO' => 11, // Colombia
        'KM' => 11, // Comoros
        'CG' => 11, // Congo
        'CD' => 11, // Congo, the Democratic Republic of the
        'CK' => 11, // Cook Islands
        'CR' => 12, // Costa Rica
        'CI' => 11, // Cote d'Ivoire
        'HR' => 12, // Croatia
        'CU' => 11, // Cuba
        'CY' => 12, // Cyprus
        'CZ' => 12, // Czech Republic
        'DK' => 12, // Denmark
        'DJ' => 11, // Djibouti
        'DM' => 11, // Dominica
        'DO' => 11, // Dominican Republic
        'TL' => 12, // East Timor
        'EC' => 12, // Ecuador
        'EG' => 13, // Egypt
        'SV' => 11, // El Salvador
        'GQ' => 11, // Equatorial Guinea
        'ER' => 11, // Eritrea
        'EE' => 12, // Estonia
        'ET' => 11, // Ethiopia
        'FK' => 11, // Falkland Islands (Malvinas)
        'FO' => 11, // Faroe Islands
        'FJ' => 11, // Fiji
        'FI' => 12, // Finland
        'FR' => 12, // France
        'GF' => 11, // French Guiana
        'PF' => 11, // French Polynesia
        'TF' => 11, // French Southern Territories
        'GA' => 11, // Gabon
        'GM' => 11, // Gambia
        'GE' => 12, // Georgia
        'DE' => 12, // Germany
        'GH' => 12, // Ghana
        'GI' => 11, // Gibraltar
        'GR' => 12, // Greece
        'GL' => 11, // Greenland
        'GD' => 11, // Grenada
        'GP' => 11, // Guadeloupe
        'GU' => 11, // Guam
        'GT' => 11, // Guatemala
        'GN' => 11, // Guinea
        'GW' => 11, // Guinea-Bissau
        'GY' => 11, // Guyana
        'HT' => 11, // Haiti
        'HM' => 11, // Heard and Mc Donald Islands
        'VA' => 11, // Holy See (Vatican City State)
        'HN' => 11, // Honduras
        'HK' => 11, // Hong Kong
        'HU' => 12, // Hungary
        'IS' => 11, // Iceland
        'IN' => 13, // India
        'ID' => 13, // Indonesia
        'IR' => 12, // Iran (Islamic Republic of)
        'IQ' => 12, // Iraq
        'IE' => 12, // Ireland
        'IL' => 11, // Israel
        'IT' => 12, // Italy
        'JM' => 11, // Jamaica
        'JP' => 12, // Japan
        'JO' => 12, // Jordan
        'KZ' => 11, // Kazakhstan
        'KE' => 12, // Kenya
        'KI' => 11, // Kiribati
        'KP' => 12, // Korea, Democratic People's Republic of
        'KR' => 12, // Korea, Republic of
        'KW' => 12, // Kuwait
        'KG' => 11, // Kyrgyzstan
        'LA' => 12, // Lao, People's Democratic Republic
        'LV' => 12, // Latvia
        'LB' => 12, // Lebanon
        'LS' => 11, // Lesotho
        'LR' => 11, // Liberia
        'LY' => 12, // Libya
        'LI' => 12, // Liechtenstein
        'LT' => 12, // Lithuania
        'LU' => 12, // Luxembourg
        'MO' => 11, // Macau
        'MK' => 11, // North Macedonia
        'MG' => 12, // Madagascar
        'MW' => 12, // Malawi
        'MY' => 11, // Malaysia
        'MV' => 12, // Maldives
        'ML' => 12, // Mali
        'MT' => 12, // Malta
        'MH' => 12, // Marshall Islands
        'MQ' => 11, // Martinique
        'MR' => 12, // Mauritania
        'MU' => 11, // Mauritius
        'YT' => 11, // Mayotte
        'MX' => 12, // Mexico
        'FM' => 11, // Micronesia, Federated States of
        'MD' => 12, // Moldova, Republic of
        'MC' => 11, // Monaco
        'MN' => 11, // Mongolia
        'MS' => 12, // Montserrat
        'MA' => 12, // Morocco
        'MZ' => 12, // Mozambique
        'MM' => 12, // Myanmar
        'NA' => 12, // Namibia
        'NR' => 11, // Nauru
        'NP' => 13, // Nepal
        'NL' => 12, // Netherlands
        'AN' => 12, // Netherlands Antilles
        'NC' => 11, // New Caledonia
        'NZ' => 11, // New Zealand
        'NI' => 11, // Nicaragua
        'NE' => 11, // Niger
        'NG' => 13, // Nigeria
        'NU' => 11, // Niue
        'NF' => 11, // Norfolk Island
        'MP' => 11, // Northern Mariana Islands
        'NO' => 12, // Norway
        'OM' => 12, // Oman
        'PK' => 13, // Pakistan
        'PW' => 12, // Palau
        'PA' => 11, // Panama
        'PG' => 11, // Papua New Guinea
        'PY' => 12, // Paraguay
        'PE' => 11, // Peru
        'PH' => 13, // Philippines
        'PN' => 11, // Pitcairn
        'PL' => 12, // Poland
        'PT' => 12, // Portugal
        'PR' => 11, // Puerto Rico
        'QA' => 12, // Qatar
        'RE' => 11, // Reunion
        'RO' => 12, // Romania
        'RU' => 11, // Russian Federation
        'RW' => 11, // Rwanda
        'KN' => 11, // Saint Kitts and Nevis
        'LC' => 11, // Saint Lucia
        'VC' => 11, // Saint Vincent and the Grenadines
        'WS' => 11, // Samoa
        'SM' => 12, // San Marino
        'ST' => 11, // Sao Tome and Principe
        'SA' => 13, // Saudi Arabia
        'SN' => 11, // Senegal
        'SC' => 11, // Seychelles
        'SL' => 11, // Sierra Leone
        'SG' => 11, // Singapore
        'SK' => 12, // Slovakia
        'SI' => 12, // Slovenia
        'SB' => 11, // Solomon Islands
        'SO' => 12, // Somalia
        'ZA' => 12, // South Africa
        'GS' => 11, // South Georgia and the South Sandwich Islands
        'ES' => 12, // Spain
        'LK' => 12, // Sri Lanka
        'SH' => 11, // Saint Helena
        'PM' => 11, // Saint Pierre and Miquelon
        'SD' => 12, // Sudan
        'SR' => 11, // Suriname
        'SJ' => 11, // Svalbard and Jan Mayen Islands
        'SZ' => 11, // Swaziland
        'SE' => 12, // Sweden
        'CH' => 12, // Switzerland
        'SY' => 12, // Syrian Arab Republic
        'TW' => 12, // Taiwan, Province of China
        'TJ' => 11, // Tajikistan
        'TZ' => 11, // Tanzania, United Republic of
        'TH' => 11, // Thailand
        'TG' => 11, // Togo
        'TK' => 11, // Tokelau
        'TO' => 11, // Tonga
        'TT' => 11, // Trinidad and Tobago
        'TN' => 12, // Tunisia
        'TR' => 12, // Turkey
        'TM' => 11, // Turkmenistan
        'TC' => 11, // Turks and Caicos Islands
        'TV' => 11, // Tuvalu
        'UG' => 11, // Uganda
        'UA' => 12, // Ukraine
        'AE' => 13, // United Arab Emirates
        'GB' => 12, // United Kingdom
        'US' => 12, // United States
        'UM' => 11, // United States Minor Outlying Islands
        'UY' => 12, // Uruguay
        'UZ' => 11, // Uzbekistan
        'VU' => 11, // Vanuatu
        'VE' => 11, // Venezuela
        'VN' => 11, // Vietnam
        'VG' => 11, // Virgin Islands (British)
        'VI' => 11, // Virgin Islands (U.S.)
        'WF' => 11, // Wallis and Futuna Islands
        'EH' => 11, // Western Sahara
        'YE' => 12, // Yemen
        'YU' => 11, // Yugoslavia
        'ZM' => 12, // Zambia
        'ZW' => 12, // Zimbabwe
    ]
];

?>