<?php

return [
    'courses' => [
    'Accounting' => 'Accounting',
    'Aerospace Engineering' => 'Aerospace Engineering',
    'Agriculture' => 'Agriculture',
    'Animation' => 'Animation',
    'Anthropology' => 'Anthropology',
    'Architecture' => 'Architecture',
    'Artificial Intelligence' => 'Artificial Intelligence',
    'Astronomy' => 'Astronomy',
    'Biology' => 'Biology',
    'Business Administration' => 'Business Administration',
    'Chemistry' => 'Chemistry',
    'Civil Engineering' => 'Civil Engineering',
    'Computer Science' => 'Computer Science',
    'Culinary Arts' => 'Culinary Arts',
    'Cybersecurity' => 'Cybersecurity',
    'Data Science' => 'Data Science',
    'Economics' => 'Economics',
    'Education' => 'Education',
    'Electrical Engineering' => 'Electrical Engineering',
    'Engineering' => 'Engineering',
    'English Literature' => 'English Literature',
    'Environmental Science' => 'Environmental Science',
    'Ethics' => 'Ethics',
    'Film Studies' => 'Film Studies',
    'Finance' => 'Finance',
    'Fine Arts' => 'Fine Arts',
    'Game Development' => 'Game Development',
    'Geology' => 'Geology',
    'Graphic Design' => 'Graphic Design',
    'History' => 'History',
    'Hospitality Management' => 'Hospitality Management',
    'Human Resource Management' => 'Human Resource Management',
    'Information Technology' => 'Information Technology',
    'International Relations' => 'International Relations',
    'Journalism' => 'Journalism',
    'Law' => 'Law',
    'Linguistics' => 'Linguistics',
    'Marine Biology' => 'Marine Biology',
    'Marketing' => 'Marketing',
    'Mathematics' => 'Mathematics',
    'Mechanical Engineering' => 'Mechanical Engineering',
    'Medicine' => 'Medicine',
    'Music' => 'Music',
    'Nursing' => 'Nursing',
    'Pharmacy' => 'Pharmacy',
    'Philosophy' => 'Philosophy',
    'Photography' => 'Photography',
    'Physical Education' => 'Physical Education',
    'Physics' => 'Physics',
    'Political Science' => 'Political Science',
    'Psychology' => 'Psychology',
    'Public Administration' => 'Public Administration',
    'Religious Studies' => 'Religious Studies',
    'Social Work' => 'Social Work',
    'Sociology' => 'Sociology',
    'Supply Chain Management' => 'Supply Chain Management',
    'Tourism' => 'Tourism',
    'Urban Planning' => 'Urban Planning',
    'Veterinary Science' => 'Veterinary Science',
],

];
