<?php

return [
    'specialization' => [
    'Actuarial Science',
    'Adult Education',
    'Aerospace Engineering',
    'Air Conditioning and Refrigeration Service',
    'Anthropology',
    'Apparel Construction',
    'Arabic',
    'Artificial Intelligence',
    'Astronomy',
    'Audio/Video Arts Technology',
    'Biology',
    'Biomedical Engineering',
    'Bread and Pastry Arts',
    'Business Administration',
    'Certified Nursing Assistant (CNA)',
    'Chemical Engineering',
    'Chemistry',
    'Chinese',
    'Civil Engineering',
    'Cloud Computing',
    'Communication Studies',
    'Computer-Aided Design (CAD)',
    'Computer Information Systems',
    'Computer Numerical Control (CNC)',
    'Construction',
    'Construction Engineering',
    'Corporate Law',
    'Criminal Justice',
    'Culinary Arts',
    'Cultural Studies',
    'Curriculum Development',
    'Cybersecurity',
    'Customer Success and Sales',
    'Data Science',
    'Database Management',
    'Dental Hygiene',
    'Dentistry',
    'Design & Architecture',
    'Desktop Publishing',
    'Diagnostic Medical Sonography',
    'Dietetic Internship',
    'Drone Technology and Applications',
    'E-Commerce',
    'E-learning',
    'Earth Sciences',
    'Early Childhood Education',
    'Economics',
    'Education',
    'Electrical Engineering',
    'Electronics Engineering',
    'Elementary Education',
    'English',
    'English as a Second Language (ESL)',
    'Entrepreneurship',
    'Environmental Science',
    'Ethics',
    'Family Child Care',
    'Fashion Design',
    'Film Studies',
    'Finance',
    'Financial Management',
    'Fine Arts',
    'Forensic Science',
    'French',
    'Game Development',
    'Genetics',
    'Geography',
    'German',
    'Graphic Arts',
    'Heating, Ventilation, Air Conditioning, and Refrigeration (HVACR)',
    'History',
    'Hospitality Management',
    'Hotel Management',
    'Human Resource Management',
    'Human-Computer Interaction',
    'Industrial Electronics Maintenance',
    'Industrial Engineering',
    'Information Systems',
    'Information Technology',
    'Insurance',
    'International Business',
    'International Law',
    'Italian',
    'Japanese',
    'Justice Administration',
    'Justice Administration and Public Safety',
    'Law',
    'Law Enforcement',
    'Legal Studies',
    'Learning Communities',
    'Librarianship',
    'Linguistics',
    'Literature',
    'Magnetic Resonance Imaging (MRI)',
    'Mammography',
    'Manufacturing Technology',
    'Marketing',
    'Material Science',
    'Mathematics',
    'Mechanical Engineering',
    'Mechatronics',
    'Medical Imaging',
    'Medical Office Administration',
    'Medicine',
    'Middle School Education',
    'Music',
    'Nanotechnology',
    'Neuroscience',
    'Networking & Cloud Computing',
    'Nursing',
    'Office Assistant',
    'Paramedic',
    'Paralegal Studies',
    'Personalized Marketing (Graphic Arts Technology)',
    'Pharmacy',
    'Philosophy',
    'Phlebotomy',
    'Photography',
    'Physical Education',
    'Physical Therapy',
    'Physics',
    'Pipe Welding',
    'Political Science',
    'Practical Nursing (PN)',
    'Private Security',
    'Programming',
    'Psychiatry',
    'Psychology',
    'Public Administration',
    'Public Health',
    'Public Safety Dispatcher',
    'Radiology',
    'Registered Nursing (RN)',
    'Religious Studies',
    'Retail Management',
    'Retail Merchandising',
    'Risk Management',
    'Robotics',
    'Russian',
    'Small Business Management',
    'Social Science',
    'Sociology',
    'Software Development',
    'Software Engineering',
    'Spanish',
    'Special Education',
    'Speech Communication',
    'Statistics',
    'Sterile Processing and Distribution',
    'Study Abroad',
    'Supply Chain Management',
    'Surgical Technology',
    'Taxation',
    'Teaching English as a Second Language (TESOL)',
    'Teaching Methodologies',
    'Textiles',
    'Theatre Arts',
    'Tourism',
    'Urdu',
    'Veterinary Science',
    'Visual Arts',
    'Web Development',
    'Welding Technology',
    'World Languages',
],
];
