<?php

return [
    'subjects' => [
        // Science & Technology
        'Physics',
        'Chemistry',
        'Biology',
        'Earth Sciences',
        'Environmental Science',
        'Astronomy',
        'Material Science',

        // Computer Science & IT
        'Programming',
        'Web Development',
        'Artificial Intelligence',
        'Cybersecurity',
        'Data Science',
        'Networking & Cloud Computing',
        'Software Development',
        'Database Management',
        'Game Development',
        'Human-Computer Interaction',
        'Computer Information Systems',
        'Software Engineering',
        'Cloud Computing',
        'Computer-Aided Design (CAD)',
        'Computer Numerical Control (CNC)',
        'Information Systems',

        // Engineering & Applied Sciences
        'Mechanical Engineering',
        'Electrical Engineering',
        'Civil Engineering',
        'Chemical Engineering',
        'Aerospace Engineering',
        'Biomedical Engineering',
        'Nanotechnology',
        'Mechatronics',
        'Robotics',
        'Industrial Engineering',
        'Construction Engineering',
        'Electronics Engineering',
        'Manufacturing Technology',
        'Industrial Electronics Maintenance',

        // Mathematics & Statistics
        'Mathematics',
        'Statistics',
        'Actuarial Science',

        // Medicine & Healthcare
        'Medicine',
        'Pharmacy',
        'Genetics',
        'Public Health',
        'Nursing',
        'Psychiatry',
        'Neuroscience',
        'Dentistry',
        'Veterinary Science',
        'Medical Imaging',
        'Physical Therapy',
        'Radiology',
        'Surgical Technology',
        'Dental Hygiene',
        'Diagnostic Medical Sonography',
        'Paramedic',
        'Phlebotomy',
        'Respiratory Care Science',
        'Certified Nursing Assistant (CNA)',
        'Medical Office Administration',
        'Practical Nursing (PN)',
        'Registered Nursing (RN)',
        'Dietetic Internship',
        'Magnetic Resonance Imaging (MRI)',
        'Mammography',
        'Sterile Processing and Distribution',

        // Business & Economics
        'Finance',
        'Marketing',
        'Human Resource Management',
        'Entrepreneurship',
        'E-Commerce',
        'Supply Chain Management',
        'International Business',
        'Economics',
        'Business Administration',
        'Accounting',
        'Risk Management',
        'Taxation',
        'Retail Management',
        'Hospitality Management',
        'Hotel Management',
        'Insurance',
        'Customer Success and Sales',
        'eMarketing',
        'Personalized Marketing (Graphic Arts Technology)',
        'Retail Merchandising',
        'Small Business Management',
        'Financial Management',

        // Social Sciences & Humanities
        'Sociology',
        'Political Science',
        'Anthropology',
        'Psychology',
        'Geography',
        'Cultural Studies',
        'Social Science',
        'Public Administration',
        'Justice Administration',
        'Law Enforcement',
        'Justice Administration and Public Safety',

        // Humanities
        'History',
        'Philosophy',
        'Linguistics',
        'Literature',
        'Religious Studies',
        'Ethics',
        'English',
        'Urdu',
        'French',
        'Spanish',
        'German',
        'Arabic',
        'Japanese',
        'Chinese',
        'Russian',
        'Italian',
        'American Sign Language',
        'World Languages',
        'Speech Communication',
        'Communication Studies',
        'English as a Second Language (ESL)',

        // Arts & Creativity
        'Visual Arts',
        'Music',
        'Performing Arts',
        'Design & Architecture',
        'Film Studies',
        'Photography',
        'Fashion Design',
        'Graphic Arts',
        'Fine Arts',
        'Theatre Arts',
        'Audio/Video Arts Technology',
        'Textiles',

        // Law & Criminology
        'Law',
        'Criminal Justice',
        'Forensic Science',
        'International Law',
        'Corporate Law',
        'Legal Studies',
        'Private Security',
        'Public Safety Dispatcher',

        // Vocational & Technical Studies
        'Air Conditioning and Refrigeration Service',
        'Desktop Publishing',
        'Construction',
        'Welding Technology',
        'Culinary Arts',
        'Bread and Pastry Arts',
        'Apparel Construction',
        'Paralegal Studies',
        'Office Assistant',
        'Heating, Ventilation, Air Conditioning, and Refrigeration (HVACR)',
        'Drone Technology and Applications',
        'Pipe Welding',
        'Industrial Electronics Maintenance',

        // Education & Pedagogy
        'Education',
        'Curriculum Development',
        'Special Education',
        'E-learning',
        'Adult Education',
        'Teaching Methodologies',
        'Librarianship',
        'Early Childhood Education',
        'Elementary Education',
        'Secondary Education',
        'Teaching English as a Second Language (TESOL)',
        'Middle School Education',
        'Physical Education',
        'Family Child Care',
        'Learning Communities',
        'Study Abroad',
    ],
];
