<?php

return [
            'universities' => [
                'National University of Sciences and Technology (NUST)',
                'Lahore University of Management Sciences (LUMS)',
                'Quaid-i-Azam University',
                'University of the Punjab',
                'COMSATS University Islamabad',
                'University of Engineering and Technology (UET) Lahore',
                'Aga Khan University',
                'Institute of Business Administration (IBA) Karachi',
                'Pakistan Institute of Engineering and Applied Sciences (PIEAS)',
                'University of Karachi',
                'Government College University (GCU) Lahore',
                'International Islamic University Islamabad (IIUI)',
                'University of Agriculture, Faisalabad',
                'NED University of Engineering and Technology',
                'FAST National University of Computer and Emerging Sciences',
                'Massachusetts Institute of Technology',
                'Harvard University',
                'Stanford University',
                'Cornell University',
                'University of California, Berkeley',
                'University of Michigan',
                'University of Washington',
                'Columbia University in the City of New York',
                'University of Oxford',
                'University of California, Los Angeles',
                'Yale University',
                'University of Pennsylvania',
                'Universidad Nacional Autónoma de México',
                'University of Wisconsin-Madison',
                'The University of Texas at Austin',
                'University of Cambridge',
                'University of Chicago',
                'Princeton University',
                'University of Minnesota Twin Cities',
                'Purdue University',
                'University of California, Davis',
                'University of Toronto',
                'University of California, San Diego',
                'Johns Hopkins University',
                'New York University',
                'Penn State University',
                'University of Florida',
                'Michigan State University',
                'University of Southern California',
                'University of North Carolina at Chapel Hill',
                'Carnegie Mellon University',
                'The University of British Columbia',
                'Arizona State University',
                'Duke University',
                'University of Maryland',
                'Rutgers, The State University of New Jersey',
                'University of Illinois Urbana-Champaign',
                'The Ohio State University',
                'University of Colorado Boulder',
                'Texas A&M University',
                'The University of Arizona',
                'University of California, Irvine',
                'Northwestern University',
                'University of Virginia',
                'University College London',
                'Boston University',
                'North Carolina State University',
                'The University of Utah',
                'Indiana University Bloomington',
                'University of New South Wales',
                'Eidgenössische Technische Hochschule Zürich',
                'Universidade de São Paulo',
                'University of California, Santa Barbara',
                'McGill University',
                'Georgetown University',
                'University of Pittsburgh',
                'University of Edinburgh',
                'Washington University in St. Louis',
                'Tufts University',
                'University of Nebraska-Lincoln',
                'Virginia Polytechnic Institute and State University',
                'The University of Sydney',
                'Oregon State University',
                'Brigham Young University',
                'Monash University',
                'University of Waterloo',
                'Georgia Institute of Technology',
                'University of Georgia',
                'University of Rochester',
                'Brown University',
                'The University of Melbourne',
                'California Institute of Technology',
                'University of Iowa',
                'Iowa State University',
                'Colorado State University',
                'University of California, San Francisco',
                'Simon Fraser University',
                'George Washington University',
                'University of Massachusetts Amherst',
                'The London School of Economics and Political Science',
                'Katholieke Universiteit Leuven',
                'George Mason University',
                'University of South Florida',
                'Washington State University',
                'Ludwig-Maximilians-Universität München',
                'Florida State University',
                'Vanderbilt University',
                'University of Alberta',
                'Syracuse University',
                'The University of Queensland',
                'Universität Wien',
                'The University of Tokyo',
                'University of Oregon',
                'Emory University',
                'University of California, Santa Cruz',
                'University of Notre Dame',
                'Australian National University',
                'Dartmouth College',
                'University of Connecticut',
                'University of Houston',
                'University at Buffalo, State University of New York',
                'University of Kentucky',
                'University of Manchester',
                'University of Illinois Chicago',
                'University of California, Riverside',
                'University of Southampton',
                'Universiteit Utrecht',
                'Imperial College London',
                'Rice University',
                'University of Glasgow',
                'Alma Mater Studiorum Università di Bologna',
                'York University',
                'University of Central Florida',
                'Universiteit van Amsterdam',
                'University of Missouri',
                'Georgia State University',
                'Technische Universiteit Delft',
                'Northeastern University',
                'University of Calgary',
                'University of Kansas',
                'Technische Universität München',
                'University of Delaware',
                'Ruprecht-Karls-Universität Heidelberg',
                'Freie Universität Berlin',
                'University of Warwick',
                'University of Birmingham',
                'Universiteit Leiden',
                'Universitetet i Oslo',
                'Universidad de Barcelona',
                'Universidad de Buenos Aires',
                'Rijksuniversiteit Groningen',
                'Helsingin yliopisto',
                'Friedrich-Alexander-Universität Erlangen-Nürnberg',
                'McMaster University',
                'Kings College London',
                'Universidad Complutense de Madrid',
                'The University of Tennessee, Knoxville',
                'University of New Mexico',
                'Kyoto University',
                'Technische Universität Berlin',
                'University of Miami',
                'École Polytechnique Fédérale de Lausanne',
                'University of North Texas',
                'Københavns Universitet',
                'University of Leeds',
                'Western University',
                'Universiteit Gent',
                'National University of Singapore',
                'Université de Montréal',
                'University of South Carolina',
                'University of Victoria',
                'Boston College',
                'Louisiana State University',
                'Universität Hamburg',
                'Florida International University',
                'Humboldt-Universität zu Berlin',
                'Ruhr-Universität Bochum',
                'San Diego State University',
                'Temple University',
                'Drexel University',
                'Universität Zürich',
                'Rheinisch-Westfälische Technische Hochschule Aachen',
                'Technische Universität Wien',
                'University of Cincinnati',
                'National Taiwan University',
                'Clemson University',
                'Università degli Studi di Padova',
                'The University of Hong Kong',
                'Universidad de Granada',
                'Newcastle University',
                'Masarykova univerzita',
                'The University of York',
                'University of New Hampshire',
                'Univerzita Karlova',
                'Norges teknisk-naturvitenskaplige universitet',
                'University of Auckland',
                'Université de Genève',
                'Rochester Institute of Technology',
                'University of Vermont',
                'Utah State University',
                'Eberhard Karls Universität Tübingen',
                'Université Laval',
                'King Saud University',
                'Tsinghua University',
                'University of Nottingham',
                'Pontificia Universidad Católica del Perú',
                'Queens University',
                'Universität zu Köln',
                'Universidad de Valencia',
                'American University',
                'University of Liverpool',
                'Rheinische Friedrich-Wilhelms-Universität Bonn',
                'Case Western Reserve University',
                'Aarhus Universitet',
                'Fordham University',
                'Virginia Commonwealth University',
                'The University of Adelaide',
                'Technische Universität Dresden',
                'Moscow State University',
                'Goethe-Universität Frankfurt am Main'
        
    ],
];
