<?php

return [
            'universities' => [
            'Aarhus Universitet',
            'Aga Khan University',
            'Alma Mater Studiorum Università di Bologna',
            'American University',
            'Arizona State University',
            'Australian National University',
            'Boston College',
            'Boston University',
            'Brigham Young University',
            'Brown University',
            'California Institute of Technology',
            'Carnegie Mellon University',
            'Case Western Reserve University',
            'Clemson University',
            'Columbia University in the City of New York',
            'COMSATS University Islamabad',
            'Colorado State University',
            'Cornell University',
            'Dartmouth College',
            'Drexel University',
            'Duke University',
            'Eberhard Karls Universität Tübingen',
            'Eidgenössische Technische Hochschule Zürich',
            'École Polytechnique Fédérale de Lausanne',
            'Emory University',
            'Florida International University',
            'Florida State University',
            'Fordham University',
            'Freie Universität Berlin',
            'Friedrich-Alexander-Universität Erlangen-Nürnberg',
            'George Mason University',
            'George Washington University',
            'Georgetown University',
            'Georgia Institute of Technology',
            'Georgia State University',
            'Government College University (GCU) Lahore',
            'Harvard University',
            'Helsingin yliopisto',
            'Humboldt-Universität zu Berlin',
            'Indiana University Bloomington',
            'Institute of Business Administration (IBA) Karachi',
            'Imperial College London',
            'International Islamic University Islamabad (IIUI)',
            'Iowa State University',
            'Johns Hopkins University',
            'Katholieke Universiteit Leuven',
            'King Saud University',
            'Kings College London',
            'Københavns Universitet',
            'Kyoto University',
            'Lahore University of Management Sciences (LUMS)',
            'Louisiana State University',
            'Ludwig-Maximilians-Universität München',
            'Massachusetts Institute of Technology',
            'Masarykova univerzita',
            'McGill University',
            'McMaster University',
            'Michigan State University',
            'Monash University',
            'Moscow State University',
            'National Taiwan University',
            'National University of Sciences and Technology (NUST)',
            'National University of Singapore',
            'NED University of Engineering and Technology',
            'New York University',
            'Newcastle University',
            'North Carolina State University',
            'Northeastern University',
            'Northwestern University',
            'Norwegian University of Science and Technology',
            'Penn State University',
            'Pontificia Universidad Católica del Perú',
            'Princeton University',
            'Purdue University',
            'Quaid-i-Azam University',
            'Queen’s University',
            'Rice University',
            'Rheinisch-Westfälische Technische Hochschule Aachen',
            'Rheinische Friedrich-Wilhelms-Universität Bonn',
            'Rijksuniversiteit Groningen',
            'Rochester Institute of Technology',
            'Ruhr-Universität Bochum',
            'Rutgers, The State University of New Jersey',
            'San Diego State University',
            'Simon Fraser University',
            'Stanford University',
            'Syracuse University',
            'Technische Universität Berlin',
            'Technische Universität Dresden',
            'Technische Universität München',
            'Technische Universität Wien',
            'Technische Universiteit Delft',
            'Temple University',
            'Texas A&M University',
            'The London School of Economics and Political Science',
            'The Ohio State University',
            'The University of Adelaide',
            'The University of Arizona',
            'The University of British Columbia',
            'The University of Hong Kong',
            'The University of Melbourne',
            'The University of Queensland',
            'The University of Sydney',
            'The University of Texas at Austin',
            'The University of Tokyo',
            'The University of Utah',
            'The University of York',
            'The University of Tennessee, Knoxville',
            'Tufts University',
            'Tsinghua University',
            'Universidad Complutense de Madrid',
            'Universidad de Barcelona',
            'Universidad de Buenos Aires',
            'Universidad de Granada',
            'Universidad de Valencia',
            'Universidad Nacional Autónoma de México',
            'Universidade de São Paulo',
            'Università degli Studi di Padova',
            'Universiteit Gent',
            'Universiteit Leiden',
            'Universiteit Utrecht',
            'Universiteit van Amsterdam',
            'Universität Hamburg',
            'Universität Wien',
            'Universität Zürich',
            'Universität zu Köln',
            'Université de Genève',
            'Université de Montréal',
            'Université de Montréal',
            'Université Laval',
            'University at Buffalo, State University of New York',
            'University College London',
            'University of Alberta',
            'University of Auckland',
            'University of Birmingham',
            'University of California, Berkeley',
            'University of California, Davis',
            'University of California, Irvine',
            'University of California, Los Angeles',
            'University of California, Riverside',
            'University of California, San Diego',
            'University of California, San Francisco',
            'University of California, Santa Barbara',
            'University of California, Santa Cruz',
            'University of Cambridge',
            'University of Calgary',
            'University of Central Florida',
            'University of Chicago',
            'University of Cincinnati',
            'University of Colorado Boulder',
            'University of Connecticut',
            'University of Delaware',
            'University of Edinburgh',
            'University of Engineering and Technology (UET) Lahore',
            'University of Florida',
            'University of Georgia',
            'University of Glasgow',
            'University of Houston',
            'University of Illinois Chicago',
            'University of Illinois Urbana-Champaign',
            'University of Iowa',
            'University of Kentucky',
            'University of Leeds',
            'University of Liverpool',
            'University of Manchester',
            'University of Maryland',
            'University of Massachusetts Amherst',
            'University of Miami',
            'University of Michigan',
            'University of Minnesota Twin Cities',
            'University of Missouri',
            'University of Nebraska-Lincoln',
            'University of New Hampshire',
            'University of New Mexico',
            'University of New South Wales',
            'University of North Carolina at Chapel Hill',
            'University of North Texas',
            'University of Notre Dame',
            'University of Nottingham',
            'University of Oxford',
            'University of Pennsylvania',
            'University of Pittsburgh',
            'University of Rochester',
            'University of Southampton',
            'University of South Carolina',
            'University of South Florida',
            'University of Southern California',
            'University of Sydney',
            'University of Texas at Austin',
            'University of Toronto',
            'University of Utah',
            'University of Victoria',
            'University of Virginia',
            'University of Warwick',
            'University of Washington',
            'University of Waterloo',
            'University of Wisconsin-Madison',
            'University of York',
            'Utah State University',
            'Vanderbilt University',
            'Virginia Commonwealth University',
            'Virginia Polytechnic Institute and State University',
            'Washington State University',
            'Washington University in St. Louis',
            'Western University',
            'Yale University',
            'York University'
        ],
];
